version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  postgresql:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb

  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-server
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: YourPassword123
      ACCEPT_EULA: Y
